#export _JAVA_AWT_WM_NONREPARENTING=1
#export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
redshift &
compton &
source /home/enrico/Git/Zsh/paths.zsh
export PATH="$PATH:/home/enrico/.bin/"
sh ~/.fehbg &
#~/.dwm/barDwm &
setxkbmap us &
xscreensaver -no-splash &
exec i3 
