xrdb -merge .Xresources
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
redshift &
export PATH="$PATH:/home/enrico/.bin/"
sh ~/.fehbg &
~/.dwm/barDwm &
setxkbmap it &
xscreensaver -no-splash &
exec dwm 
