# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
autoload -U compinit promptinit
compinit
promptinit; prompt gentoo
export ZSH=/home/enrico/.oh-my-zsh
export PATH="$PATH:/home/enrico/.bin/"
export EDITOR='vim'
export VISUAL='vim' 
export TESI=/home/enrico/Git/Tesi
# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="gentoo"



# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
#ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias gentoo-update="su -c 'emerge-webrsync'"
alias gentoo-upgrade="su -c 'emerge -av -uDU --with-bdeps=y @world'"
alias gentoo-use-new="emerge -av --update --newuse --deep @world"
alias spegni="su -c 'shutdown -h now'"
alias connect="su -c '/etc/init.d/net.wlp2s0 start'"
alias copy="xclip -f -sel clip"
alias paste="xclip -o -sel clip"
alias scrotF="scrot -b -d 5 ~/Pictures/%b%d::%H%M%S.png"
#alias ubuntu="VBoxManage startvm 'Lubuntu14.04' --type gui"
#alias Arch="VBoxManage startvm 'Arch' --type gui"
alias display="xrandr --output HDMI1 --auto && xrandr --output eDP1 --off"
alias nodisplay="xrandr --output HDMI1 --off && xrandr --output eDP1 --auto"
alias reboot="su -c 'reboot'"
alias uranger="urxvt -e ranger"
alias scrubs="su -c 'btrfs scrub start /'"
alias old_root="su -c 'mount UUID=6792A3A8-6E5F-470A-8807-45CCB0140AD0 \
                /mnt/ROOT_old'"
alias layit="su -c 'setxkbmap it'"
alias layus="su -c 'setxkbamp en'"
alias dualdisp="xrandr --output eDP1 --left-of HDMI1 --auto; feh --bg-scale ~/Pictures/Lattice.png --bg-scale ~/Pictures/yosmite.png"
